name: todopool
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  flutter_easyloading: ^3.0.5  
  dio: ^5.4.3+1
  smooth_page_indicator: ^1.1.0 
  uuid: ^4.4.0
  result_dart: ^1.1.1
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0
  triple: ^2.1.0
  firebase_auth: ^4.19.5
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  wakelock_plus: ^1.2.5
  path: ^1.9.0 
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  dart_debouncer: ^1.1.0
  go_router: ^14.0.2
  syncfusion_flutter_datepicker: ^25.1.42
  syncfusion_flutter_sliders: ^25.1.42
  syncfusion_flutter_core: ^25.1.42
  syncfusion_flutter_gauges: ^25.1.42 
  dotted_border: ^2.1.0
  enchanted_collection: ^1.3.0
  date_picker_plus: ^3.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true  
