// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4eOZrDqfjjf4Toe0yP-d1iwjeefUoGiI',
    appId: '1:1028560305178:web:3906e0633d9b31646c25a3',
    messagingSenderId: '1028560305178',
    projectId: 'todopool',
    authDomain: 'todopool.firebaseapp.com',
    storageBucket: 'todopool.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ9WZyR-MFgWpUJKSnwHyrCFZhT3ykGG4',
    appId: '1:1028560305178:android:027da5e996e852796c25a3',
    messagingSenderId: '1028560305178',
    projectId: 'todopool',
    storageBucket: 'todopool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQzf7XOS2FCCWcvBlR9-3YaIJd0nC37Yw',
    appId: '1:1028560305178:ios:cf5007a7058c87f36c25a3',
    messagingSenderId: '1028560305178',
    projectId: 'todopool',
    storageBucket: 'todopool.appspot.com',
    iosBundleId: 'com.knowmore.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQzf7XOS2FCCWcvBlR9-3YaIJd0nC37Yw',
    appId: '1:1028560305178:ios:4121e071c9af1bfb6c25a3',
    messagingSenderId: '1028560305178',
    projectId: 'todopool',
    storageBucket: 'todopool.appspot.com',
    iosBundleId: 'com.pooltodo.todopool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4eOZrDqfjjf4Toe0yP-d1iwjeefUoGiI',
    appId: '1:1028560305178:web:dcec2972d3c89edc6c25a3',
    messagingSenderId: '1028560305178',
    projectId: 'todopool',
    authDomain: 'todopool.firebaseapp.com',
    storageBucket: 'todopool.appspot.com',
  );
}
